Console.WriteLine("Введите координату точки х1");
int x1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координату точки y1");
int y1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координату точки z1");
int z1 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координату точки х2");
int x2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координату точки y2");
int y2 = Convert.ToInt32(Console.ReadLine());
Console.WriteLine("Введите координату точки z2");
int z2 = Convert.ToInt32(Console.ReadLine());
double s = Math.Round(Convert.ToDouble(Math.Sqrt(Math.Pow((x2-x1),2)+Math.Pow((y2-y1),2)+Math.Pow((z2-z1),2))),2);
Console.WriteLine($"Расстояние между точками = {s}");